language: haskell
matrix:
  include:
  - ghc: "7.8"
  - ghc: "7.10"
  - ghc: "8.0"
  - ghc: "8.2"
  - ghc: "8.4"
script: travis_wait 70 cabal configure --enable-tests && travis_wait 70 cabal build && cabal test
