name:                quickselect
version:             0.1.0.0
github:              "oisdk/quickselect"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/quickselect#readme>

dependencies:
- base == 4.*
- vector >= 0.7

library:
  source-dirs: src
  other-modules: Control.Applicative.LiftMany

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

tests:
  quickselect-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quickselect
    - QuickCheck >= 2.4
  quickselect-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - quickselect
    - doctest
    - QuickCheck

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - quickselect
    - criterion
    - random
